# **2.4 System of Linear Equations**

* **Ax=b**
* A = coefficient matrix 
* x = unknown vector 
* b = constant vector

## **Inverse Matrix**

* $A^{-1}A = AA^{-1} = I$

* Inverse matrix is a squared matrix 
* Some matrices does not have inverse matrix (invertible matrix vs. non-invertible matrix)

* $(A^T)^{-1} = (A^{-1})^T$

* $(AB)^{-1} = B^{-1}A^{-1}$
* $(ABC)^{-1} = C^{-1}B^{-1}A^{-1}$

* $A^{-1} = \frac{1}{det(A)}C^T$
* Inverse matrix exists when determinant is not $0$

## **Sherman-Morrison Formula**

* $(A+uv^T)^{-1} = A^{-1} - \frac{A^{-1}uv^TA^{-1}}{1+v^TA^{-1}u}$

In [2]:
import numpy as np

A = np.array([[1,1,0],[0,1,1],[1,1,1]])
A

array([[1, 1, 0],
       [0, 1, 1],
       [1, 1, 1]])

In [2]:
Ainv = np.linalg.inv(A)
Ainv

array([[ 0., -1.,  1.],
       [ 1.,  1., -1.],
       [-1.,  0.,  1.]])

In [3]:
A @ Ainv

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## **Inverse matrix, and the solution of linear equation system**

* $Ax=b$
* $A^{-1}Ax = A^{-1}b$
* $Ix = A^{-1}b$
* **$x = A^{-1}b$**

In [4]:
b = np.array([[2],[2],[3]])
b

array([[2],
       [2],
       [3]])

In [5]:
x = Ainv @ b
x

array([[1.],
       [1.],
       [1.]])

In [6]:
A @ x - b

array([[0.],
       [0.],
       [0.]])

In [5]:
x, resid, rank, s = np.linalg.lstsq(A, b)
x

<ipython-input-5-e7b8f111164f>:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  x, resid, rank, s = np.linalg.lstsq(A, b)


array([[1.],
       [1.],
       [1.]])

## **2.4.5 Boston House Prices**

In [6]:
import numpy as np
from sklearn.datasets import load_boston

In [7]:
boston = load_boston()
X = boston.data
y = boston.target
A = X[:4, [0,4,5,6]] # 'CRIM', 'NOX', 'RM', 'AGE'
b = y[:4]

In [8]:
x = np.linalg.inv(A) @ b
x

array([-3.12710043e+02, -1.15193942e+02,  1.44996465e+01, -1.13259317e-01])

## **Pseudo Inverse**

* $A^+=(A^TA)^{-1}A^T$

* $x=A^+b$

In [9]:
A = np.array([[1,1,0],[0,1,1],[1,1,1],[1,1,2]])
A

array([[1, 1, 0],
       [0, 1, 1],
       [1, 1, 1],
       [1, 1, 2]])

In [11]:
b = np.array([[2],[2],[3],[4.1]])
b

array([[2. ],
       [2. ],
       [3. ],
       [4.1]])

In [13]:
Apinv = np.linalg.inv(A.T @ A) @ A.T
Apinv

array([[ 0.33333333, -1.        ,  0.33333333,  0.33333333],
       [ 0.5       ,  1.        ,  0.        , -0.5       ],
       [-0.5       ,  0.        ,  0.        ,  0.5       ]])

In [14]:
x = Apinv @ b 
x

array([[1.03333333],
       [0.95      ],
       [1.05      ]])

In [15]:
A @ x 

array([[1.98333333],
       [2.        ],
       [3.03333333],
       [4.08333333]])

In [17]:
x, resid, rank, s = np.linalg.lstsq(A, b)
x

<ipython-input-17-e7b8f111164f>:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  x, resid, rank, s = np.linalg.lstsq(A, b)


array([[1.03333333],
       [0.95      ],
       [1.05      ]])

* $resid$ is $(e=Ax-b)^2$, the **squared norm**

In [18]:
resid, np.linalg.norm(A @ x-b)**2

(array([0.00166667]), 0.0016666666666666698)

In [19]:
from sklearn.datasets import load_boston
boston = load_boston()

In [20]:
X = boston.data
y = boston.target

In [26]:
x, resid, rank, s = np.linalg.lstsq(X, y)
x

<ipython-input-26-b587b70bb035>:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  x, resid, rank, s = np.linalg.lstsq(X, y)


array([-9.28965170e-02,  4.87149552e-02, -4.05997958e-03,  2.85399882e+00,
       -2.86843637e+00,  5.92814778e+00, -7.26933458e-03, -9.68514157e-01,
        1.71151128e-01, -9.39621540e-03, -3.92190926e-01,  1.49056102e-02,
       -4.16304471e-01])