# **2.4 System of Linear Equations**

* **Ax=b**
* A = coefficient matrix 
* x = unknown vector 
* b = constant vector

## **Inverse Matrix**

* $A^{-1}A = AA^{-1} = I$

* Inverse matrix is a squared matrix 
* Some matrices does not have inverse matrix (invertible matrix vs. non-invertible matrix)

* $(A^T)^{-1} = (A^{-1})^T$

* $(AB)^{-1} = B^{-1}A^{-1}$
* $(ABC)^{-1} = C^{-1}B^{-1}A^{-1}$

* $A^{-1} = \frac{1}{det(A)}C^T$
* Inverse matrix exists when determinant is not $0$

## **Sherman-Morrison Formula**

* $(A+uv^T)^{-1} = A^{-1} - \frac{A^{-1}uv^TA^{-1}}{1+v^TA^{-1}u}$

In [1]:
import numpy as np

A = np.array([[1,1,0],[0,1,1],[1,1,1]])
A

array([[1, 1, 0],
       [0, 1, 1],
       [1, 1, 1]])

In [2]:
Ainv = np.linalg.inv(A)
Ainv

array([[ 0., -1.,  1.],
       [ 1.,  1., -1.],
       [-1.,  0.,  1.]])

In [3]:
A @ Ainv

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## **Inverse matrix, and the solution of linear equation system**

* $Ax=b$
* $A^{-1}Ax = A^{-1}b$
* $Ix = A^{-1}b$
* **$x = A^{-1}b$**

In [4]:
b = np.array([[2],[2],[3]])
b

array([[2],
       [2],
       [3]])

In [5]:
x = Ainv @ b
x

array([[1.],
       [1.],
       [1.]])

In [6]:
A @ x - b

array([[0.],
       [0.],
       [0.]])